[project]
name = "lkg-gen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.98.0",
    "tqdm>=4.67.1",
    "streamlit>=1.39.0",
    "networkx>=3.4.2",
    "pyvis>=0.3.2",
]
